### ISSUE TITLE
Swift 3 Syntax issue Adding a scheduler

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Game-Of-Life-SpriteKit-Swift3#12] opened 2016-08-19 23:17 UTC
[action] Add the following code to `didMoveToView(...)`

Should read:

[action] Add the following code to `didMove(to view: SKView)`

The code block below this should be updated to: 

```
/* Create an SKAction based timer, 0.5 second delay */
let delay = SKAction.wait(forDuration: 0.5)

/* Call the stepSimulation() method to advance the simulation */
let callMethod = SKAction.perform(#selector(GameScene.stepSimulation), onTarget: self)

/* Create the delay,step cycle */
let stepSequence = SKAction.sequence([delay,callMethod])

/* Create an infinite simulation loop */
let simulation = SKAction.repeatForever(stepSequence)

/* Run simulation action */
self.run(simulation)

/* Default simulation to pause state */
self.isPaused = true
```

**Comment by esscbee** [comment] 2016-08-20 17:10
duplicate of #11

**Closed as completed by esscbee** 2016-08-20 17:10 UTC
